-- MySQL Script generated by MySQL Workbench
-- Wed Oct  1 04:21:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema air_cargo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema air_cargo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `air_cargo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `air_cargo` ;

-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

CREATE TABLE IF NOT EXISTS `customer` (
  `customer_id` INT NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `gender` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `passengers_on_flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passengers_on_flights` ;

CREATE TABLE IF NOT EXISTS `passengers_on_flights` (
  `customer_id` INT NOT NULL,
  `aircraft_id` VARCHAR(20) NULL DEFAULT NULL,
  `route_id` INT NULL DEFAULT NULL,
  `depart` VARCHAR(50) NULL DEFAULT NULL,
  `arrival` DECIMAL(50) NULL DEFAULT NULL,
  `seat_num` VARCHAR(20) NULL DEFAULT NULL,
  `class_id` VARCHAR(20) NULL DEFAULT NULL,
  `travel_date` DATE NOT NULL,
  `flight_num` INT NOT NULL,
  `passengers_on_flightscol` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`, `travel_date`, `flight_num`),
  INDEX `fk_passenger_route_idx` (`route_id` ASC) VISIBLE,
  CONSTRAINT `fk_passenger_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passenger_route`
    FOREIGN KEY (`route_id`)
    REFERENCES `routes` (`route_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `routes` ;

CREATE TABLE IF NOT EXISTS `routes` (
  `route_id` INT NOT NULL,
  `flight_num` INT NULL,
  `origin_airport` VARCHAR(20) NULL DEFAULT NULL,
  `destination_airport` DECIMAL(20) NULL DEFAULT NULL,
  `aircraft_id` VARCHAR(20) NULL DEFAULT NULL,
  `distance_miles` INT NULL DEFAULT NULL,
  PRIMARY KEY (`route_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ticket_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_details` ;

CREATE TABLE IF NOT EXISTS `ticket_details` (
  `p_date` DATE NOT NULL,
  `customer_id` INT NOT NULL,
  `aircraft_id` VARCHAR(20) NOT NULL,
  `class_id` VARCHAR(20) NULL DEFAULT NULL,
  `no_of_tickets` INT NULL DEFAULT NULL,
  `a_code` VARCHAR(20) NULL DEFAULT NULL,
  `Price_per_ticket` DECIMAL(10,2) NULL DEFAULT NULL,
  `brand` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`, `aircraft_id`, `p_date`),
  CONSTRAINT `fk_ticket_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
